### ISSUE TITLE
Mod causes problems with player interaction permissions

### ISSUE THREAD

**Issue by rkxspace** [ninjagoku4560/Iseeitall#6]
The mod, while great, has several problems. Players cannot eat and containers are not fully functional unless made an operator.

**Comment by RX0kas** [comment]
Thanks for alerting me, may I know if you are on the latest version?  
I will resolve this problem as soon as possible

**Comment by rkxspace** [comment]
I had downloaded the latest version for 1.20.4 on Modrinth

**Comment by rkxspace** [comment]
I will test this in different environments when possible.

**Comment by RX0kas** [comment]
I find a way to fix this issue.
I just need to finish a new feature and I publish it as quickly as I can
